github.com:
    users:
        HyperAfnan:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: HyperAfnan
